### ISSUE TITLE
Cannot find module 'querystring' when using in React-Native app

### ISSUE THREAD

**Issue by fzymek** [bttmly/nba#48]
Hello,

I am trying to use this module in react-native app but I am getting following error:

```
error: bundling failed: Error: Unable to resolve module `querystring` from `/Users/zymfilip/Development/src/NBABrowseApp/node_modules/nba/src/stats.js`: Module does not exist in the module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
```

I tried proposed solution but it does not work. Here's my env setup:

```
node v6.13.1
npm v3.10.10
nba v4.2.0
```

**Comment by bttmly** [comment]
Try `nba@4.2.1` – I've removed `querystring` as a dependency. Please let me know if it works or not when you get a chance!

**Comment by fzymek** [comment]
hmm.. now I am getting the same error but for different module:

```
Unable to resolve module `url` from `/Users/zymfilip/Development/src/NBABrowseApp/node_modules/nba/src/get-json.js`: Module does not exist in the module map
```

it seems to be related to react-native and the issue they are mentioning in error log [https://github.com/facebook/react-native/issues/4968](https://github.com/facebook/react-native/issues/4968)

I tried creating simple node app and it works without a problem. Both 4.2.0 and 4.2.1

**Comment by bttmly** [comment]
Hm alright yeah so react-native can't pull in Node.js builtin modules (both `querystring` and `url` are provided by Node.js but included in the browser build by Browserify).

Question for you: do you have the global `URL` constructor available in react-native? It's a browser feature https://developer.mozilla.org/en-US/docs/Web/API/URL

**Comment by bttmly** [comment]
I added an explicit [`url` dependency](https://www.npmjs.com/package/url) in `nba@4.2.2` – can you try that one? Sorry for the back-and-forth

**Comment by fzymek** [comment]
No problem, but still no luck ;( 

```
error: bundling failed: Error: Unable to resolve module `http` from `/Users/zymfilip/Development/src/NBABrowseApp/node_modules/node-fetch/index.js`: Module does not exist in the module map

This might be related to https://github.com/facebook/react-native/issues/4968
```

Regarding `URL`, it looks that there are some issues with `URL` in RN [](https://github.com/facebook/react-native/issues/16434) lately. 

It seems that there are some conflicts as I tried adding dependency on `http` module in my app and I got following error:

```
error: bundling failed: Error: While trying to resolve module `http` from file `/Users/zymfilip/Development/src/ReactiveAirQuality/node_modules/node-fetch/index.js`, the package `/Users/zymfilip/Development/src/ReactiveAirQuality/node_modules/http/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/zymfilip/Development/src/ReactiveAirQuality/node_modules/http/index.js`. Indeed, none of these files exist:

  * `/Users/zymfilip/Development/src/ReactiveAirQuality/node_modules/http/index.js(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
  * `/Users/zymfilip/Development/src/ReactiveAirQuality/node_modules/http/index.js/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
```

It seems to me (but I might be wrong as I am quite new to node & react-native) that you are using some dependencies not supported in RN.  Is it possible?

**Comment by bttmly** [comment]
Yes that's exactly the problem: `url`, `querystring`, and `http` all come from NodeJS 
https://nodejs.org/api/http.html
https://nodejs.org/api/url.html
https://nodejs.org/api/querystring.html

what if you try:

```js
import nba from "nba/dist/nba"
```

**Comment by fzymek** [comment]
Still no luck

```
error: bundling failed: Error: Unable to resolve module `./src` from `/Users/zymfilip/Development/src/ReactiveAirQuality/node_modules/nba/dist/nba.js`: The module `./src` could not be found from `/Users/zymfilip/Development/src/ReactiveAirQuality/node_modules/nba/dist/nba.js`. Indeed, none of these files exist:

  * `/Users/zymfilip/Development/src/ReactiveAirQuality/node_modules/nba/dist/src(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
  * `/Users/zymfilip/Development/src/ReactiveAirQuality/node_modules/nba/dist/src/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
```

**Comment by bttmly** [comment]
Damn. Alright, I'll try compiling it with webpack instead of browserify and see if that helps. I'll get back to you in a couple days

**Comment by binbinla** [comment]
same issue here.

**Comment by bttmly** [comment]
This totally slipped my mind. Now that the season is about to start... I just published `nba@4.3.2` can someone try using `import nba from "nba/dist/webpacked"`?

**Comment by MatthewDevelop** [comment]
just use npm install querystring
it works for me

**Comment by bttmly** [comment]
great! closing, but if someone else runs into a similar problem please open an issue

**Comment by giacomocerquone** [comment]
@MatthewDevelop Just porting a node crypto dependant project into react-native and solved that package's querystring dependency like this!
Love you

**Comment by ajaymarathe** [comment]
> just use npm install querystring
> it works for me

Works for me too :)
