### ISSUE TITLE
Help about schedule

### ISSUE THREAD

**Issue by moelfassi** [bttmly/nba#50]
Hi, is there any way to get schedule: 'https://stats.nba.com/schedule/' for like a month..
 i can only get daily games with:
`NBA.stats.scoreboard({gameDate: "10/01/2018"}).then(console.log);`
please help

**Comment by jcbalcita** [comment]
this endpoint seems to send back the entire season's schedule: https://data.nba.com/data/10s/v2015/json/mobile_teams/nba/2018/league/00_full_schedule_week.json

**Comment by moelfassi** [comment]
> this endpoint seems to send back the entire season's schedule: https://data.nba.com/data/10s/v2015/json/mobile_teams/nba/2018/league/00_full_schedule_week.json

exactly what i need.. Thank you
