### ISSUE TITLE
Endpoint with the most up-to-date scores

### ISSUE THREAD

**Issue by garyking** [bttmly/nba#55]
[This endpoint](http://data.nba.com/data/5s/json/cms/noseason/scoreboard/20181008/games.json) (which is used in [this library](https://github.com/jaebradley/nba-stats-client)) has by far the most up-to-date scores (within seconds of the live score). In comparison, the source currently in use by the `nba` library is often delayed by about 5 minutes of game-time, and even [this source](https://stats.nba.com/stats/scoreboardV2?DayOffset=0&LeagueID=00&gameDate=10%2F08%2F2018) (which is the basis of [this page](https://stats.nba.com/scores/10/05/2018) as mentioned in #54) is often delayed by about a minute of game-time. 

Please consider using the first URL mentioned in this post. I imagine the format is different though, so that might be a problem? I know that a number of NBA apps on GitHub use the other library for the most up-to-date scores, but this library for general player stats, etc.

Otherwise, at least consider using the second source, which I believe is the same format as the source currently in use by this library.

**Comment by bttmly** [comment]
released in `nba@4.4.0` under `nba.data.scoreboard()` method here https://github.com/bttmly/nba/blob/master/src/data.js#L11-L20 (endpoints in this package are namespaced by the NBA's URL naming scheme)

**Comment by garyking** [comment]
Great thanks, that works well.
