### ISSUE TITLE
`data` endpoint: Add box score and play-by-play

### ISSUE THREAD

**Issue by garyking** [bttmly/nba#56]
Thanks for adding the `data.scoreboard` method. Please also add these `data` endpoints too:

- [Box score](http://data.nba.com/data/5s/json/cms/noseason/game/20181008/0011800047/boxscore.json)
  - Format: `/data/5s/json/cms/noseason/game/{DATE}/{GAME_ID}/boxscore.json`
- [Play by play](http://data.nba.com/data/5s/json/cms/noseason/game/20181008/0011800047/pbp_all.json)
  - Format: `/data/5s/json/cms/noseason/game/{DATE}/{GAME_ID}/pbp_all.json`

The `DATE`s are in `YYYYMMDD` format. The `GAME_ID`s are from the `data.scoreboard` endpoint.

**Comment by bttmly** [comment]
published in `nba@4.5.0` as `nba.data.boxScore(date, gameId)` and `nba.data.playByPlay(date, gameId)`
