### ISSUE TITLE
Team Stats - Advanced

### ISSUE THREAD

**Issue by dtkavana** [bttmly/nba#61]
NBA.stats.teamStats({ TeamID: 1610612737 }).then(response => {
      this.atlantaStats = response;
    });

I have this call setup, but was wondering how you would drill down to a team's Advanced stats - such as Offensive Rating, Defensive Rating, etc. This call returns what appears to be the "Traditional" stats.

Thanks

**Comment by bttmly** [comment]
try this:
```

**Comment by dtkavana** [comment]
ahhh, measure type! Thank you
