### ISSUE TITLE
Failed to minify the code

### ISSUE THREAD

**Issue by mattphoto** [bttmly/nba#64]
using create-react-app

npm run build

```
Failed to minify the code from this file: 

 	./node_modules/nba/src/get-json.js:24 

Read more here: http://bit.ly/2tRViJ9

npm ERR! code ELIFECYCLE
```

**Comment by bttmly** [comment]
It seems like this client is getting more difficult to use on the client-side as most of the new endpoints seem to not support CORS requests or JSONP. What endpoints are you currently able to use?

**Comment by mattphoto** [comment]
I just using the standings endpoint NBA.stats.leagueStandings() currently. http://bballstandings.com/ Plan to add boxscore visualization in the future. suggestions/advice appreciated.

**Comment by bttmly** [comment]
due to CORS restrictions imposed by nba.com this library doesn't really function in the browser anymore. It needs to be used on the server with Node.js, or used to write scripts to pull statistics and populate a database
