### ISSUE TITLE
Live box score data

### ISSUE THREAD

**Issue by jcostello93** [bttmly/nba#66]
I noticed that the scoreboard endpoint is updated while games are being played, but the two box score endpoints (boxScore and boxScoreSummary) aren't. Do you know any other way to get live box score data using this module?

**Comment by jcostello93** [comment]
Found the endpoint: 

https://data.nba.net/prod/v1/20190421/0041800134_boxscore.json

**Comment by bttmly** [comment]
Is that endpoint supported by the library already? If not, pull requests welcome

**Comment by jcostello93** [comment]
NBA.data.boxScore calls a different endpoint with a slightly different response format, but it also returns live box score data. 

NBA.data.playByPlay also returns live data while NBA.stats.boxScore and NBA.stats.playByPlay do not.

**Comment by bttmly** [comment]
As far as I can tell, they are trying to move their endpoints to the `/data` namespace so if there is duplicated functionality between `NBA.stats` and `NBA.data`, use `data`
