### ISSUE TITLE
`nba.stats.scoreboard`: No way to get game start time

### ISSUE THREAD

**Issue by garyking** [bttmly/nba#84]
With `nba.stats.scoreboard`, it seems like if the game is live, then there's no way to get its start time?

**Comment by bttmly** [comment]
try using `nba.data.scoreboard`, the stats namespace endpoints are old and it seems like nba.com is deprecating them.

**Comment by garyking** [comment]
Are there does on `nba.data.scoreboard`? I can't seem to find any.

**Comment by bttmly** [comment]
Ah interesting. No, sorry, I don't really have the bandwidth to document the data endpoints right now. The purpose of this library is largely to find endpoints and give a simple JS API for them. I would be interested in writing an automated tool that discerned the response shape from a sample response but haven't gotten to them. However I try to put in a basic test for each endpoint (https://github.com/bttmly/nba/blob/master/test/integration/data.js). You can run that test file with mocha with a WITH_LOGS environment variable to log the response shape.

**Comment by garyking** [comment]
The endpoint once again stopped working. 

[This](http://data.nba.com/data/5s/json/cms/noseason/scoreboard/20200115/games.json) returns `File not found."` right now.

**Comment by garyking** [comment]
I went to [this page](https://ca.global.nba.com/scores/#!/2020-01-16) and checked Chrome's `Network` tab for XHR requests. That led me to [this useful JSON](https://ca.global.nba.com/stats2/scores/daily.json?countryCode=CA&gameDate=2020-01-16&locale=en&tz=-5).
