### ISSUE TITLE
Missing `data` endpoints

### ISSUE THREAD

**Issue by garyking** [bttmly/nba#85]
- calendar: http://data.nba.net/data/10s/prod/v1/calendar.json
- standings: http://data.nba.net/data/10s/prod/v1/current/standings_all.json
- teams: http://data.nba.net/data/10s/prod/v1/2019/teams.json

**Comment by bttmly** [comment]
awesome thanks! how'd you come across these? I'm writing a crawler that will try to traverse NBA.com and find URLs like this but I haven't seen these before.

**Comment by garyking** [comment]
I just found them online, from other libraries, while looking for endpoints for things that I needed.

**Comment by bttmly** [comment]
which libraries? I'm trying to amass as many sources as I can so I can automate endpoint discovery,

**Comment by garyking** [comment]
I don't remember where I got them from. I just Googled for "nba api calendar" etc.

**Comment by oniyou** [comment]
standing url now is not work.
