### ISSUE TITLE
NBA API - required headers

### ISSUE THREAD

**Issue by dtkavana** [bttmly/nba#86]
I believe that the NBA has updated the required headers which causes this package to fail when making requests. The API calls appear to just hang.

**Comment by bttmly** [comment]
Ugh thats a bummer. The `data.nba.com` endpoints still seem to work. The `stats.nba.com` endpoints seem to be getting progressively flakier and harder to use. Still trying to find a good way to gather `data.nba.com` endpoints so that we can retire stats.

**Comment by bttmly** [comment]
Found the necessary headers here https://github.com/swar/nba_api/issues/124

Fixed in `nba@4.13`
