### ISSUE TITLE
players.json missing 2021 rookies

### ISSUE THREAD

**Issue by domini7** [bttmly/nba#98]
Hey, having fun with this client. Noticed this years rookies aren't in `players.json` yet after trying to search for them. Just letting you know you.

**Comment by bttmly** [comment]
I'll make a release with updated players soon. You can always update the internal list of players at runtime by calling `NBA.updatePlayers()`

**Comment by bttmly** [comment]
Weird! the players endpoint only seems to be returning the first 150ish players, rather than the 450ish you'd expect (30 teams * 15 spots)
